language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:secret --quiet
  - touch storage/database_testing.sqlite
  - php artisan migrate

cache:
  directories:
    - vendor
